FROM python:3.10

WORKDIR /app

RUN apt-get update
RUN apt-get install -y postgresql-client

COPY . /app/

RUN pip install -r requirements.txt

VOLUME ["/data"]

EXPOSE 8501

CMD ["uvicorn", "interface.main:app", "--host", "0.0.0.0", "--port", "8501"]