FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

VOLUME ["/data"]

EXPOSE 8501

CMD ["uvicorn", "interface.main:app", "--host", "0.0.0.0", "--port", "8501"]