apiVersion: apps/v1
kind: Deployment
metadata:
  name: interface
  labels:
    app: interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interface
  template:
    metadata:
      labels:
        app: interface
    spec:
      containers:
      - name: interface
        image: dockerge-interface
        imagePullPolicy: "Never"
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: interface-configmap
        - secretRef:
            name: interface-secret