apiVersion: v1
kind: Service
metadata:
  name: interface-service
  labels:
    app: interface
spec:
  selector:
    app: interface
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
